const express = require('express');
const rateLimit = require('express-rate-limit');
const { requireAuth } = require('../middleware/authMiddleware');
const controller = require('../controllers/conversationController');
const router = express.Router();
const writeLimiter = rateLimit({ windowMs: 60 * 1000, limit: 40, standardHeaders: 'draft-7', legacyHeaders: false, message: { success: false, message: 'Too many conversation requests.' } });
router.use(requireAuth);
router.get('/', controller.listConversations);
router.post('/direct', writeLimiter, controller.createDirect);
router.post('/group', writeLimiter, controller.createGroup);
router.get('/:id', controller.getConversation);
router.get('/:id/messages', controller.getMessages);
router.patch('/:id/mute', writeLimiter, controller.setMute);
router.post('/:id/clear', writeLimiter, controller.clearConversation);
router.patch('/:id/group', writeLimiter, controller.renameGroup);
router.post('/:id/members', writeLimiter, controller.addMembers);
router.delete('/:id/members/:userId', writeLimiter, controller.removeMember);
router.post('/:id/leave', writeLimiter, controller.leaveGroup);
module.exports = router;
