const path=require('path');const crypto=require('crypto');
const Conversation=require('../models/Conversation');const Message=require('../models/Message');const User=require('../models/User');
const {uploadBuffer,deleteAsset,optimizedImageUrl,signedAssetUrl}=require('../config/cloudinary');const {IMAGE_MIMES}=require('../middleware/uploadMiddleware');
const {SAFE_USER_FIELDS,findAuthorizedConversation}=require('../utils/conversationHelpers');const {serializeMessage}=require('./conversationController');
function cleanName(value){return path.basename(value).replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,120);}function rooms(c){return[`conversation:${c._id}`,...c.members.map((m)=>`user:${m.user}`)];}
async function emitMessage(req,c,m){const populated=await Message.findById(m._id).populate('sender',SAFE_USER_FIELDS);const payload=serializeMessage(populated);req.app.get('io')?.to(rooms(c)).emit('message:new',payload);return payload;}
async function uploadAttachments(req,res,next){const uploaded=[];try{const clientMessageId=String(req.body.clientMessageId||''),caption=String(req.body.caption||'').trim();if(!clientMessageId||clientMessageId.length>100||caption.length>2000)return res.status(400).json({success:false,message:'Invalid attachment message.'});const duplicate=await Message.findOne({sender:req.userId,clientMessageId}).populate('sender',SAFE_USER_FIELDS);if(duplicate)return res.json({success:true,message:serializeMessage(duplicate),duplicate:true});for(const file of req.files){const image=IMAGE_MIMES.has(file.mimetype);const result=await uploadBuffer(file.buffer,{kind:image?'image':'file',publicId:`${Date.now()}-${crypto.randomUUID()}`});uploaded.push({url:image?optimizedImageUrl(result.public_id,{width:1280}):signedAssetUrl(result.public_id,'raw'),publicId:result.public_id,resourceType:result.resource_type,originalName:cleanName(file.originalname),mimeType:file.mimetype,format:result.format||path.extname(file.originalname).slice(1),size:file.size,width:result.width,height:result.height,uploadedBy:req.userId});}const type=uploaded.every((item)=>item.resourceType==='image')?'image':'file';const message=await Message.create({conversation:req.conversation._id,sender:req.userId,clientMessageId,type,text:caption,attachments:uploaded,deliveredTo:[req.userId],readBy:[req.userId]});await Conversation.updateOne({_id:req.conversation._id},{$set:{lastMessage:message._id,lastMessageAt:message.createdAt},$inc:{'members.$[recipient].unreadCount':1}},{arrayFilters:[{'recipient.user':{$ne:req.userId}}]});return res.status(201).json({success:true,message:await emitMessage(req,req.conversation,message)});}catch(error){await Promise.allSettled(uploaded.map((item)=>deleteAsset(item.publicId,item.resourceType)));next(error);}}
async function uploadAvatar(req,res,next){let uploaded;try{const result=await uploadBuffer(req.file.buffer,{kind:'profile',publicId:`${req.userId}-${crypto.randomUUID()}`});uploaded={url:optimizedImageUrl(result.public_id,{width:400}),publicId:result.public_id};const previous=req.user.avatar?.publicId;await User.updateOne({_id:req.userId},{$set:{avatar:uploaded}});if(previous)await deleteAsset(previous,'image').catch(()=>{});await broadcastProfile(req,{url:uploaded.url});return res.json({success:true,message:'Profile photo updated.',avatar:{url:uploaded.url}});}catch(error){if(uploaded?.publicId)await deleteAsset(uploaded.publicId,'image').catch(()=>{});next(error);}}
async function removeAvatar(req,res,next){try{const publicId=req.user.avatar?.publicId;await User.updateOne({_id:req.userId},{$set:{avatar:{url:null,publicId:null}}});if(publicId)await deleteAsset(publicId,'image').catch(()=>{});await broadcastProfile(req,null);return res.json({success:true,message:'Profile photo removed.',avatar:null});}catch(error){next(error);}}
async function broadcastProfile(req,avatar){const related=await Conversation.distinct('members.user',{'members.user':req.userId});const ids=new Set([String(req.userId),...related.map(String)]);req.app.get('io')?.to([...ids].map((id)=>`user:${id}`)).emit('profile:updated',{userId:String(req.userId),username:req.user.username,avatar});}
async function recordDownload(req,res,next){try{const message=await Message.findById(req.params.messageId);if(!message)return res.status(404).json({success:false,message:'Attachment not found.'});const conversation=await findAuthorizedConversation(message.conversation,req.userId,false);if(!conversation)return res.status(404).json({success:false,message:'Attachment not found.'});const index=Number(req.params.index),attachment=message.attachments[index];if(!attachment)return res.status(404).json({success:false,message:'Attachment not found.'});const event=await Message.create({conversation:conversation._id,sender:req.userId,clientMessageId:`download:${req.userId}:${message._id}:${index}:${Date.now()}`,type:'event',text:`${req.user.username} downloaded ${attachment.originalName}`,eventType:'attachment_downloaded',eventData:{messageId:String(message._id),attachmentIndex:index,originalName:attachment.originalName},deliveredTo:[req.userId],readBy:[req.userId]});await Conversation.updateOne({_id:conversation._id},{$set:{lastMessage:event._id,lastMessageAt:event.createdAt},$inc:{'members.$[recipient].unreadCount':1}},{arrayFilters:[{'recipient.user':{$ne:req.userId}}]});const payload=await emitMessage(req,conversation,event);req.app.get('io')?.to(rooms(conversation)).emit('attachment:downloaded',payload);return res.json({success:true,url:attachment.url,event:payload});}catch(error){next(error);}}
module.exports={uploadAttachments,uploadAvatar,removeAvatar,recordDownload};
